# Generated by Django 4.2.8 on 2023-12-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Messages', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
